# Generated by Django 4.1.4 on 2023-11-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCSSAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Senior_Management_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=40)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploaded/galleries')),
            ],
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-heading',)},
        ),
    ]
