# Generated by Django 4.1.4 on 2023-11-15 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCSSAPP', '0002_senior_management_image_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senior_management_image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploadedimages'),
        ),
    ]
